import Head from 'next/head';
import Image from 'next/image';
import React, { useState, useEffect, useRef } from 'react';

export default function Home() {
  const [data, setData] = useState([]);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const containerRef = useRef(null);

  const getDatas = async () => {
    const arr = [
      {
        _id: 1,
        imgUrl:
          'https://res.cloudinary.com/dewa3t2gi/image/upload/v1679647145/myportfolioblogproject/aqez1mh3xrycdslmxm25.gif',
      },
      {
        _id: 2,
        imgUrl:
          'https://res.cloudinary.com/dewa3t2gi/image/upload/v1677818589/myportfolioblogproject/ta2ew0kg9unlstsv3g3m.gif',
      },
      {
        _id: 3,
        imgUrl:
          'https://res.cloudinary.com/dewa3t2gi/image/upload/v1679554666/myportfolioblogproject/qae9fi8bjtpuoc5qjse7.gif',
      },
      {
        _id: 4,
        imgUrl:
          'https://res.cloudinary.com/dewa3t2gi/image/upload/v1678437768/myportfolioblogproject/qpyzc9k1w06m1ldplwmw.gif',
      },
      {
        _id: 5,
        imgUrl:
          'https://res.cloudinary.com/dewa3t2gi/image/upload/v1676974927/myportfolioblogproject/od9rqmzhmhdmwusqk5qe.gif',
      },
    ];
    setData([...data, ...arr]);
    setPage(page + 1);

    setLoading(false);
    return;
  };

  useEffect(() => {
    const handleScroll = () => {
      const { scrollTop, clientHeight, scrollHeight } = containerRef.current;
      console.log(scrollTop, clientHeight, scrollHeight);
      if (scrollTop + clientHeight >= scrollHeight) {
        getDatas();
      }
    };

    containerRef.current.addEventListener('scroll', handleScroll);

    return () => {
      containerRef.current.removeEventListener('scroll', handleScroll);
    };
  }, [data]);

  useEffect(() => {
    getDatas();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className='container'
        ref={containerRef}
        style={{
          width: '140%',
          height: '100vh',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          overflowY: 'auto',
        }}
      >
        {data.map((d, i) => (
          <div key={i} style={{ objectFit: 'cover' }}>
            <Image
              src={d.imgUrl}
              alt={d._id}
              style={{ objectFit: 'cover' }}
              width={700}
              height={300}
            />
          </div>
        ))}
      </div>
    </>
  );
}
