import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import Slider from 'react-slick';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

export default function Home() {
  const [currentSlide, setCurrentSlide] = useState(1);
  const [totalImgNum, setTotalImgNum] = useState();
  const [imgArr, setImgArr] = useState([]);

  const settings = {
    dots: true, // 하단에 동그라미로 표시되는 페이지네이션
    infinite: true, // 무한 스크롤링
    speed: 500, // 슬라이드 전환 속도 (ms)
    slidesToShow: 1, // 화면에 보여질 슬라이드 개수
    slidesToScroll: 1, // 한 번에 스크롤될 슬라이드 개수
    autoplay: true, // 자동 넘김
    beforeChange: (current, next) => setCurrentSlide(next),
  };

  useState(() => {
    setImgArr([
      'https://res.cloudinary.com/dewa3t2gi/image/upload/v1679647145/myportfolioblogproject/aqez1mh3xrycdslmxm25.gif',
      'https://res.cloudinary.com/dewa3t2gi/image/upload/v1677818589/myportfolioblogproject/ta2ew0kg9unlstsv3g3m.gif',
      'https://res.cloudinary.com/dewa3t2gi/image/upload/v1679554666/myportfolioblogproject/qae9fi8bjtpuoc5qjse7.gif',
      'https://res.cloudinary.com/dewa3t2gi/image/upload/v1678437768/myportfolioblogproject/qpyzc9k1w06m1ldplwmw.gif',
      'https://res.cloudinary.com/dewa3t2gi/image/upload/v1676974927/myportfolioblogproject/od9rqmzhmhdmwusqk5qe.gif',
    ]);
  }, []);

  useEffect(() => {
    setTotalImgNum(imgArr.length);
  }, [imgArr]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Slider {...settings} focusOnSelect={false}>
        {imgArr.map((img, index) => (
          <div>
            <img src={img} alt={`slide${index}`} />
          </div>
        ))}
      </Slider>
      <div style={{ textAlign: 'center', position: 'relative', top: '2rem' }}>
        <span>{currentSlide + 1}</span> / <span>{totalImgNum}</span>
      </div>
    </>
  );
}
